spring.application.name=mascotas

spring.datasource.url=jdbc:mysql://localhost:3306/mascotas_db
spring.datasource.username=root
spring.datasource.password=1234

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD:changeit}
server.ssl.key-alias=mascotas-local
server.port=8443
server.forward-headers-strategy=framework

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
