spring:
  application:
    name: CatalogueManagement

  datasource:
    url: jdbc:h2:mem:CatalogueManagement;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: true

