spring.application.name=PrimerProyectoSpringAI
spring.config.import=optional:file:./apikey.properties
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=${OPENROUTER_BASE_URL}
spring.ai.openai.chat.options.model=${OPENROUTER_MODEL}
