spring.application.name=app-spring-ai
spring.config.import=optional:file:./apikey.properties
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=${GEMINI_MODEL}
spring.ai.google.genai.chat.options.temperature=0.7
