server.port=8080
spring.application.name=clima
server.error.include-message=always
spring.config.import=optional:file:./apikey.properties
openweather.api.url=https://api.openweathermap.org/data/2.5/weather
openweather.api.key=
